language: python

python:
  - "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-qt4-dev python-m2crypto python-mock

# Skip the install stage
install: true

script: "./make.py test"

branches:
  only:
    - master

# Allow M2Crypto to be found
virtualenv:
  system_site_packages: true
